name: health_check
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.3+3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

# --- KONFIGURASI ICON LAUNCHER (Di sini, sejajar dengan dev_dependencies) ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo_aplikasi.png" 
  min_sdk_android: 21

# --- KONFIGURASI FLUTTER UTAMA ---
flutter:
  # Baris ini SANGAT PENTING agar icon muncul
  # Pastikan menjorok 2 spasi ke dalam
  uses-material-design: true 

  # assets:
  #   - images/a_dot_burr.jpeg